stages:
  -build
  -linting

build:
  stage: build
  script:
    - python -m pip install --upgrade pip
    - python -m pip install -r requirements/test.txt

flake8:
  stage: linting
  script:
    - flake8 . --count --show-source --statistics --inline-quotes 'double'

black:
  stage: linting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check --line-length 79 -- .