stages:
  - build
  - linting
  - test

build:
  stage: build
  script:
    - python -m pip install -r requirements/test.txt
    - pip install flake8-quotes flake8-import-order pep8-naming

flake8:
  stage: linting
  script:
    - flake8 .

black:
  stage: linting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black -- .

django-tests:
  stage: test
  script:
    - mv test.env .env
    - cd lyceum
    - python manage.py test