# Generated by Django 4.2.6 on 2023-10-19 21:39

import catalog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Дайте товару имя', max_length=150, verbose_name='Название')),
                ('is_published', models.BooleanField(default=True, help_text='Статус публикации', verbose_name='Опубликовано')),
                ('slug', models.CharField(help_text='Укажите слаг товара', max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[-_A-Za-z0-9\\s]+$')], verbose_name='Слаг')),
                ('weight', models.IntegerField(help_text='Укажите вес товара', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32767)], verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Дайте товару имя', max_length=150, verbose_name='Название')),
                ('is_published', models.BooleanField(default=True, help_text='Статус публикации', verbose_name='Опубликовано')),
                ('slug', models.CharField(help_text='Укажите слаг товара', max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[-_A-Za-z0-9\\s]+$')], verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Дайте товару имя', max_length=150, verbose_name='Название')),
                ('is_published', models.BooleanField(default=True, help_text='Статус публикации', verbose_name='Опубликовано')),
                ('text', models.TextField(default='', help_text='Опишите товар', validators=[catalog.models.ValidateMustContain('превосходно', 'роскошно')], verbose_name='Текст')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
                ('tags', models.ManyToManyField(default='', to='catalog.tag')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
