# Generated by Django 4.2.6 on 2023-10-24 19:44

import catalog.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Дайте товару имя', max_length=150, unique=True, verbose_name='название')),
                ('is_published', models.BooleanField(default=True, help_text='Статус публикации', verbose_name='опубликовано')),
                ('slug', models.CharField(help_text='Укажите слаг товара', max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[-_A-Za-z0-9\\s]+$')], verbose_name='слаг')),
                ('weight', models.IntegerField(default=100, help_text='Укажите вес товара', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32767)], verbose_name='вес')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Дайте товару имя', max_length=150, unique=True, verbose_name='название')),
                ('is_published', models.BooleanField(default=True, help_text='Статус публикации', verbose_name='опубликовано')),
                ('slug', models.CharField(help_text='Укажите слаг товара', max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[-_A-Za-z0-9\\s]+$')], verbose_name='слаг')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Дайте товару имя', max_length=150, unique=True, verbose_name='название')),
                ('is_published', models.BooleanField(default=True, help_text='Статус публикации', verbose_name='опубликовано')),
                ('image', models.ImageField(blank=True, default=None, help_text='Главная картинка товара', upload_to='catalog/images/main_images/', verbose_name='главная картинка')),
                ('text', models.TextField(default='', help_text='Опишите товар', validators=[catalog.validators.ValidateMustContain('превосходно', 'роскошно')], verbose_name='текст')),
                ('category', models.ForeignKey(default='', help_text='Выберите категорию', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='catalog.category', verbose_name='категория')),
                ('tags', models.ManyToManyField(default='', help_text='Добавьте теги. P.S.:', related_name='tags', to='catalog.tag', verbose_name='теги')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, help_text='Картинка для товара (переделается в 300x300)', upload_to='catalog/images/item_images/', verbose_name='картинка')),
                ('item', models.ForeignKey(help_text='Товар к которому добавить картинку', on_delete=django.db.models.deletion.CASCADE, related_name='item', to='catalog.item', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'картинка',
                'verbose_name_plural': 'картинки',
            },
        ),
    ]
