# Generated by Django 4.2.6 on 2023-10-21 12:00

import catalog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('catalog', '0001_initial'), ('catalog', '0002_alter_category_options_alter_item_options_and_more'), ('catalog', '0003_alter_category_weight')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Дайте товару имя', max_length=150, unique=True, verbose_name='название')),
                ('is_published', models.BooleanField(default=True, help_text='Статус публикации', verbose_name='опубликовано')),
                ('slug', models.CharField(help_text='Укажите слаг товара', max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[-_A-Za-z0-9\\s]+$')], verbose_name='слаг')),
                ('weight', models.IntegerField(default=100, help_text='Укажите вес товара', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32767)], verbose_name='вес')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Дайте товару имя', max_length=150, unique=True, verbose_name='название')),
                ('is_published', models.BooleanField(default=True, help_text='Статус публикации', verbose_name='опубликовано')),
                ('slug', models.CharField(help_text='Укажите слаг товара', max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[-_A-Za-z0-9\\s]+$')], verbose_name='слаг')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Дайте товару имя', max_length=150, unique=True, verbose_name='название')),
                ('is_published', models.BooleanField(default=True, help_text='Статус публикации', verbose_name='опубликовано')),
                ('text', models.TextField(default='', help_text='Опишите товар', validators=[catalog.models.ValidateMustContain('превосходно', 'роскошно')], verbose_name='текст')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
                ('tags', models.ManyToManyField(default='', to='catalog.tag')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
