# Generated by Django 4.2.6 on 2023-10-21 10:46

import catalog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Статус публикации', verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Дайте товару имя', max_length=150, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(help_text='Укажите слаг товара', max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[-_A-Za-z0-9\\s]+$')], verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.IntegerField(default=100, help_text='Укажите вес товара', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32767)], verbose_name='вес'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Статус публикации', verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Дайте товару имя', max_length=150, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(default='', help_text='Опишите товар', validators=[catalog.models.ValidateMustContain('превосходно', 'роскошно')], verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Статус публикации', verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Дайте товару имя', max_length=150, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(help_text='Укажите слаг товара', max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[-_A-Za-z0-9\\s]+$')], verbose_name='слаг'),
        ),
    ]
