# Generated by Django 4.2.6 on 2023-10-24 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='item',
            field=models.ForeignKey(help_text='Товар к которому добавить картинку', on_delete=django.db.models.deletion.CASCADE, related_name='item', to='catalog.item', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default='', help_text='Выберите категорию', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='catalog.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='main_image',
            field=models.ImageField(blank=True, default=None, help_text='Добавьте картинку для товара (она переделается в 300x300)', upload_to='catalog/images/main_images/', verbose_name='картинка для товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(default='', help_text='Добавьте теги. P.S.:', related_name='tags', to='catalog.tag', verbose_name='теги'),
        ),
    ]
