# Generated by Django 4.2.6 on 2023-11-01 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='main_image',
            field=models.ForeignKey(default=None, help_text='главная картинка для товара', on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='catalog.mainimage', verbose_name='главная картинка'),
        ),
    ]
