# Generated by Django 4.2.6 on 2023-11-03 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('catalog', '0003_alter_item_main_image'), ('catalog', '0004_remove_item_main_image_mainimage_item'), ('catalog', '0005_alter_images_item')]

    dependencies = [
        ('catalog', '0002_alter_item_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='main_image',
        ),
        migrations.AddField(
            model_name='mainimage',
            name='item',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='catalog.item'),
        ),
        migrations.AlterField(
            model_name='images',
            name='item',
            field=models.ForeignKey(help_text='Товар к которому добавить картинку', on_delete=django.db.models.deletion.CASCADE, related_name='image', to='catalog.item', verbose_name='товар'),
        ),
    ]
