# Generated by Django 4.2.6 on 2023-11-01 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_item_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='main_image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='catalog.mainimage'),
        ),
    ]
