# Generated by Django 4.2.6 on 2023-10-21 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.IntegerField(default=100, help_text='Укажите вес товара', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32767)], verbose_name='вес'),
        ),
    ]
