# Generated by Django 4.2.6 on 2023-10-24 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_image_item_main_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='main_image',
            new_name='image',
        ),
    ]
