# Generated by Django 4.2.6 on 2023-10-25 17:22

import catalog.validators
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_image_item_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', help_text='Опишите товар', validators=[catalog.validators.ValidateMustContain('превосходно', 'роскошно')], verbose_name='текст'),
        ),
    ]
