# Generated by Django 4.2.6 on 2023-11-02 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_category_item_categor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='categor',
            new_name='category',
        ),
    ]
