# Generated by Django 4.2.6 on 2023-11-03 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_rename_categor_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainimage',
            name='item',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='main_image', related_query_name='main_image', to='catalog.item'),
        ),
    ]
